### ISSUE TITLE
general questions about sending messages mechanism

### ISSUE THREAD

**Issue by serangelicloud** [AnnikaV9/hcclient#5]
I was trying to implement an encrypting method of my own at my messages, to do so i need to encrypt the message before sending it to the server, may you please explain what function handles the message string?

**Comment by AnnikaV9** [comment]
The message string is handled by `send_input()` 
https://github.com/AnnikaV9/hcclient/blob/beb32a2265efeeb52192808ddfbea7500667df4e/src/hcclient/__main__.py#L539

Note that this function also processes commands, so you'll want to make sure your encryption is done after the function has checked if the string is not a command and meant to be a message.  This is the line that finally sends a regular chat message:
https://github.com/AnnikaV9/hcclient/blob/beb32a2265efeeb52192808ddfbea7500667df4e/src/hcclient/__main__.py#L935

Also make sure to check if the message begins with a `/` anyway, since we pass some commands like `/whisper` and `/me` to the server to handle.

Feel free to ask anything else :D

**Comment by serangelicloud** [comment]
ok so i was doing a test trying to see if i could mess with the string by adding a dot at the end but apparently it's not working. 
`self.send(json.dumps({"cmd":` "chat", "text": f"{message}."}))`

any suggestions?

**Comment by AnnikaV9** [comment]
Hmm, not sure why it isn't working for you. I've tested on my side and it does append a period to messages.


https://github.com/AnnikaV9/hcclient/assets/68383195/69a44ff9-09ce-4556-8a8b-439d93c946a9

**Comment by serangelicloud** [comment]
Can you share the full code you've used?

**Comment by AnnikaV9** [comment]
I modified this snippet:

https://github.com/AnnikaV9/hcclient/blob/850ae8e7c1912d0764472ebb5fa964b383fdf0b4/src/hcclient/__main__.py#L941-L949

to

```python
 case _: 
     if self.whisper_lock: 
         if not message.split(" ")[0] in ("/whisper", "/w", "/reply", "/r") or message.startswith(" "): 
             self.print_msg("{}|{}| {}".format(termcolor.colored("-NIL-", self.args["timestamp_color"]), 
                                               termcolor.colored("CLIENT", self.args["client_color"]), 
                                               termcolor.colored("Whisper lock active, toggle it off to send messages", self.args["client_color"]))) 
             return 
  
     self.send(json.dumps({"cmd": "chat", "text": f"{message}."})) 
```

The change is at line 949 specifically

(There have been a few commits adding unrelated stuff, so the line number isn't the same as before)

**Comment by AnnikaV9** [comment]
Can you fork and add your changes so I can see your code? I'm puzzled as to why it doesn't add a period for you.

**Comment by serangelicloud** [comment]
done.

**Comment by AnnikaV9** [comment]
Just tested, works as expected. Are you maybe accidentally testing with a different installation of hcclient? Maybe one you have installed globally

![231122_21-32-55](https://github.com/AnnikaV9/hcclient/assets/68383195/a583672b-2f26-4e23-8b8c-58cca3788013)

**Comment by serangelicloud** [comment]
oh.. that was funny, thank you
sorry for disturbing :D

**Comment by AnnikaV9** [comment]
It's okay, glad we clarified it. Have a great day :D
